name: build-windows
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install -e .[build]
      - run: python -m PyInstaller --noconfirm --clean --name AvitoRawExport --collect-all nicegui --paths src src/avito_raw_export/__main__.py
      - uses: actions/upload-artifact@v4
        with:
          name: AvitoRawExport-Windows
          path: dist/AvitoRawExport/**
